import "./globals.css";

import { BookType } from "@/lib/features/books/booksSlice";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import StoreProvider from "@/lib/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchBooks = async () => {
  const response = await fetch('http://localhost:3000/booksData.json');
  if (!response.ok) {
    return { books: [], error: 'Error on getting book list'};
  }
  const books: BookType[] = await response.json();
  return { books, error: ''};
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { books, error } = await fetchBooks();
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider books={books} error={error} >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
